### ISSUE TITLE
GltfGen meshes don't load when deployed to Openode

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#107]
The functional test for gltf generation works fine when running localhost on PC, but fails to load geometry when it's deployed to Openode.io, with a 404 for the path: http://<prefix>openode.io//buffers/sphere.glb

I Suspect Server.registerStaticBuffer doesn't form the path properly, whereas, other functional tests that load static meshes (such as "${this.baseUrl}/monkey.glb") work fine

**Comment by stevenvergenz** [comment]
Fixed #114
