### ISSUE TITLE
Non-looping Keyframe animations doesn't always stop at the end frame

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#13]
In AltspaceVR, it seems keyframe animations sometimes don't stop exactly at the last frame if they are in 'once' mode.
Repro steps:
1. In the Hello World sample, in generateSpinKeyframes, remove the last frame.
2. During the DoAFlip animation creation, change duration from 1.0 to 0.5, so the animation executes quicker
3. Build, Launch, and instantiate the MRE
4. Click on the cube
Observed: Sometimes the cube stops spinning a little early (or a little late?), and sometimes it stops pointing straight up.
Expected: After the rapid spin, the cube should always stop with the top pointing straight up

**Comment by eanders-MS** [comment]
Fixed by #108
