### ISSUE TITLE
AltspaceVR: Instantiate user-uploaded Unity asset bundles

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#134]
If possible, we should find a way to have the CreateFromLibrary for AltspaceVR instantiate user-uploaded Unity Asset Bundles for both kits and worlds

**Comment by sorenhan** [comment]
(Clarified that the intent of this issue was to cover worlds also).

**Comment by stevenvergenz** [comment]
Hmm, what would it mean for an MRE to instantiate a world? Seems counter to the design goals of the MRE SDK.

**Comment by sorenhan** [comment]
I'm closing this because we support kits, and as steven says, "instantiate a world" doesn't make sense. If we want to access elements in a world, that's already covered by #158 and #54
