### ISSUE TITLE
Feature Request: personal/single-user actor

### ISSUE THREAD

**Issue by sorenhan** [microsoft/mixed-reality-extension-sdk#137]
As part of "player masking", we want the ability to have an actor that only exists on a single client, and is never synchronized to other machines - other machines won't get any data about that actor at all.

This is different than actual masking, because for all other player masking all actors are syncrhonzied to all hosts - they are just not rendered or listening to input for a subset of users. .

Physics: it would probably need to use a separate physics layer than regular actors. It would be OK for this actor to react to regular actors, but it can't affect regular actors because then regular actor behavior depends on which machine is running the physics simulation.

These actors would also be helpful when we implement command buffer playback on behavior actions - these actors could support a lot more types of commands without risk of desyncing everything.

Example use cases: A poker game: there is a regular actor with the blank card for each user's cards. Then each of those cards would have a child single-user actor with the actual face of the card. that way nobody else could see what the user has, they would just see a blank - and they would be unable to sniff their own socket connection to find out more information.

**Comment by sorenhan** [comment]
#137 (player masking) covers a lot of other scenarios, and would be used in conjunction with this - for example the first person shooter scenario where a player has a single-user actor "hand+weapon" mesh, and there is a full-body avatar actor which is excluded for the player itself but visible for everyone esle.

**Comment by stevenvergenz** [comment]
Added in #314 (Version 0.11)
