### ISSUE TITLE
Update lerna config to use a single version number for all packages

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/mixed-reality-extension-sdk#138]

**Comment by sorenhan** [comment]
With the new development process, our branches and build processes are tied to all packages having the same version number, and being released simultaneously. While there is some amount of wasted bandwidth with re-releasing zero-change packages, the simplicity that comes with always releasing together and matching numbers makes this tradeoff worth it.

**Comment by stevenvergenz** [comment]
Wouldn't this require abandoning semver for at least one package in the meta-repo?
