### ISSUE TITLE
Improve animation synchronization

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#162]
The way animation timing is synchronized right now is subject to some error due to network latencies. It also has a weak point where it relies on a peer's response, which could fail. This should be improved.

**Comment by sorenhan** [comment]
This should be redone to match the soundinstance synchronization pattern

**Comment by sorenhan** [comment]
#239 should be completed before this work is completed, as animation needs the same abilities as sound.
