### ISSUE TITLE
Feature Request: look-at should support actors whose geometry is oriented along the wrong axis

### ISSUE THREAD

**Issue by AndreMuis** [Microsoft/mixed-reality-extension-sdk#168]
For example, the frog always faces the user but the skull always faces away. I believe this depends on the orientation of the object set in the software that created them.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/920149/52181998-6642f380-27ad-11e9-9424-e78fab6e04d9.gif)

[look-at.ts.txt](https://github.com/Microsoft/mixed-reality-extension-sdk/files/2825953/look-at.ts.txt)

**Comment by stevenvergenz** [comment]
It's very unlikely the assets will be updated to face the right way. We need to implement a way to specify the forward direction when using lookAt.

**Comment by AndreMuis** [comment]
Seems like you want that to be an angle between 0 and 360. Intrinsic / local orientation? Something like that. And you might even want something to face away from you in certain situations.

**Comment by stevenvergenz** [comment]
A previous incarnation of the lookAt API supported using the actor's transform rotation in addition to lookAt, so you would rotate relative to the look. Maybe we need to bring that back. @eanders-MS ?

**Comment by eanders-MS** [comment]
It is coming back. LookAt discussion delayed due to inclement weather.

**Comment by eanders-MS** [comment]
@stevenvergenz Curious why the bug label. Which part of this is a bug?

**Comment by AndreMuis** [comment]
Feature request at this point since it looks like having all assets, especially ones created outside of MS, facing forward wouldn't be doable.

**Comment by AndreMuis** [comment]
I can't change labels. Not sure if you want people outside of MS doing that.

**Comment by sorenhan** [comment]
LookAt should now have a backwards flag

**Comment by AndreMuis** [comment]
Works now. Maybe the designer created the object at some angle other than 0 or 180 but also this might never come up.
