### ISSUE TITLE
Materials do not apply correctly to plane actor

### ISSUE THREAD

**Issue by AndreMuis** [Microsoft/mixed-reality-extension-sdk#174]
Looks like the color of a single pixel is applied to the entire plane.

original texture:

https://altspacevr-demo.herokuapp.com/beach-ball.png

![capture](https://user-images.githubusercontent.com/920149/52301738-fd3fb500-293f-11e9-8cbf-3a3b0b8dfe5b.PNG)

[plane-material.ts.txt](https://github.com/Microsoft/mixed-reality-extension-sdk/files/2833705/plane-material.ts.txt)

**Comment by stevenvergenz** [comment]
Whoops, my bad. Fixed, going into next release.

**Comment by stevenvergenz** [comment]
https://github.com/Microsoft/mixed-reality-extension-unity/pull/23

**Comment by AndreMuis** [comment]
verified fixed
