### ISSUE TITLE
Materials disappear when actor moves

### ISSUE THREAD

**Issue by AndreMuis** [Microsoft/mixed-reality-extension-sdk#175]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/920149/52303373-a9839a80-2944-11e9-8b1a-d73091162f4b.gif)

[material-disappears.ts.txt](https://github.com/Microsoft/mixed-reality-extension-sdk/files/2833808/material-disappears.ts.txt)

**Comment by eanders-MS** [comment]
Whoa! I have a hunch we've fixed this in the latest changes. Lots of cleanup has been done to the systems at play here.

**Comment by stevenvergenz** [comment]
I can't reproduce this bug in the testbed in red. Applied materials are preserved. I think you're right @eanders-MS, fixed.

**Comment by AndreMuis** [comment]
verified fixed
