### ISSUE TITLE
AltspaceVR: Experiment with realtime lights affecting actors

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#185]
Experiment with having lights affecting actors in AltspaceVR - 
1. experimental - disabled by default, but goal to eventually make them on by default on pc.
2. what should we do for default ambient color? scan the scene for directional lights, and lower default if directional lights are found? (We could even make a ambient light component, and if found in scene then use that instead of the default). It shouldn't be a shader check, but a c# global check

**Comment by stevenvergenz** [comment]
Coming soon! Four-light vertex shading with specular support.

![sdk-lights](https://user-images.githubusercontent.com/1882376/52507895-b6ec8f00-2ba7-11e9-86f0-3450de181d8b.gif)

Regarding ambient and directional lights, they're currently based on the environment and skybox of the loaded space. We'll need a larger conversation about how much control MREs should have over the shared environment if we want apps to customize this.

**Comment by eanders-MS** [comment]
So good!
