### ISSUE TITLE
Textures not tiling on plane actor

### ISSUE THREAD

**Issue by AndreMuis** [Microsoft/mixed-reality-extension-sdk#190]
When uSegments and vSegments are set to 2 the texture still spans the entire plane shown on the right.

![capture](https://user-images.githubusercontent.com/920149/52739393-bbd58800-2f85-11e9-9506-20f590b61027.PNG)

[plane-tiling.ts.txt](https://github.com/Microsoft/mixed-reality-extension-sdk/files/2861939/plane-tiling.ts.txt)

**Comment by stevenvergenz** [comment]
This isn't a bug. the u and v segments count on primitives controls the number of subdivisions, not the texture tiling. If you want to tile a texture, you need to use [Material.mainTextureScale](https://microsoft.github.io/mixed-reality-extension-sdk/classes/material.html#maintexturescale).

**Comment by AndreMuis** [comment]
works
