### ISSUE TITLE
Expose app-relative actor transforms

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/mixed-reality-extension-sdk#205]
We currently only expose the local transform of the actor. This makes it hard to do positional math between objects in hierarchies. World transform is also needed in order to track the position of actors attached to avatars (incoming feature).

"World" transform would actually be app-relative.
```ts
// local position (exists now):
actor.transform.position;
// app-relative position:
actor.world.position;
```

We should probably rename `transform` to `local`:
```ts
actor.transform.position -> actor.local.position;
```

**Comment by eanders-MS** [comment]
Soren mentioned that the world transform is a well-established concept with expectations that aren't true here. I agree with that.

Maybe `app` would be better. The notion of an app-relative transform is unique to MREs (where the location of the app in the scene is the origin), so `app` could work. Putting `transform` first would make it more discoverable and give it some context:
```ts
actor.transform.local.position;
actor.transform.app.position;
```
Just throwing out possibilities. We can lock a design next week.

**Comment by eanders-MS** [comment]
An approach that would be back-compatible would be to not have the `local` field at all, just adding `app`. The type would look something like:
```ts
type ActorTransform = Transform & {
    app: Transform;
};
```
And use it exactly how we do now, unless you want to access the app coordinates. In that case you'd go though the `app` field:
```ts
actor.transform.position; // local position
actor.transform.app.position; // app-relative position
```
Sorry for the Saturday spam!

**Comment by tombuMS** [comment]
Out for review. PR#[284](https://github.com/Microsoft/mixed-reality-extension-sdk/pull/284)
