### ISSUE TITLE
Cleanup old sound instances in sync layer

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#239]
Not critical.

**Comment by sorenhan** [comment]
Was accidentally marked as fixed - we only fixed this in the unity side, not the sync layer

**Comment by sorenhan** [comment]
There are 3 separate cases to deal with:
1. non-looping sounds expire after a certain amount of time - should clean themselves up
2. when an actor is freed, the sound instances should be freed, too
3. when a sound asset is freed, it should find and free those sound isntances, too
