### ISSUE TITLE
Send MREAPI.Logger.LogXXXXX() text through to Node.js 

### ISSUE THREAD

**Issue by sorenhan** [microsoft/mixed-reality-extension-sdk#24]
When an MRE is instantiated, and the client has errors, the errors should be sent back to the MRE, so they can be piped through to where developers expect it. By default I would expect it to show up in the Visual Studio Debug Console, and in Node.js' log files.

Examples where I would expect errors to show up
If an MRE client tries to play an animation that doesn't exist on an actor
If MRE fail to load a GLTF
If MRE tries to access an actor that doesn't exist

**Comment by eanders-MS** [comment]
Add an onError handler to context.

**Comment by eanders-MS** [comment]
Design: Add a "log-message" payload that can be sent any time from the client. Just need to log it (no onError handler). Log it to the "engine" facility.

**Comment by sorenhan** [comment]
Changed description to highlight that we already have MRE Unity logging APIs, we just don't push them through
