### ISSUE TITLE
test failure: multiple functional tests fail test with multiple users disconnecting and reconnecting

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#251]
in mre testbed, using synchronization test unity scene, if sound test is running, and instance B disconnects and reconnects, and instance A disconnects and reconnects, the server seems to freeze and various game objects get lost

**Comment by sorenhan** [comment]
I have reproduced this in the lights test as well, with the testbed/VSCode.. It wasn't consistently reproducing, but running multiple tests and being inside a test when it happens may have increased likelihood of failure. 

Observed: when rejoining, the main actors (light, cubes, monkey head) are not synchronizing, text above the test is green instead of yellow (as if the test has succeeded), and pause/resume buttons don't work. It's almost as if the text has been told it has succeeded, and started to clean up, but didn't finish

It may have to do with animation syncing, but I'm not sure.  There were multiple weird messages in the log, which may be related (and which we ought want to clean up):
[ERROR] ClientSync client f9fecf32 received unexpected reply message! payload: object-spawned, replyToId: 1ed2fa50-c3b5-4ab6-880a-3503a98de338
[ERROR] ClientSync client f9fecf32 has no handler for payload set-animation-state!
[ERROR] ClientSync client f9fecf32 has no handler for payload set-animation-state!
[ERROR] ClientSync client f9fecf32 received unexpected reply message! payload: object-spawned, replyToId: 863cbcf9-ad85-4732-9eaf-2c633fcb14ef
[ERROR] ClientSync client f9fecf32 has no handler for payload set-animation-state!
[ERROR] ClientSync client f9fecf32 has no handler for payload set-animation-state!
[ERROR] ClientSync client f9fecf32 has no handler for payload set-animation-state!
[

**Comment by eanders-MS** [comment]
Thanks Soren. This and any other sync issues are my priority next week.

**Comment by eanders-MS** [comment]
Fixed by removal of queued destroy actor command on Unity side.
