### ISSUE TITLE
Audio sync fails intermittently

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#262]
When testing the audio functional test with multiple users in the space, sounds would not start for some users.
With 5 users in the space:
- Background music would not start for one user, despite repeated starts and stops.
- Doppler sound did not play for a different user.

**Comment by stevenvergenz** [comment]
Re: doppler sound, I don't think that's a sync issue. It never played for that user (the only user on Android), over multiple runs of the test. Need to retest as authoritative user.

**Comment by eanders-MS** [comment]
Doppler didn't play for me, on PC.

**Comment by stevenvergenz** [comment]
More issues:
* The music seems to auto-play some/most of the time

**Comment by sorenhan** [comment]
OK, I've reproduced this on Quest, and I believe issue may have been that the sample downloaded the music file from a very slow and unreliable website, and never finished. After including a new music file into the SDK, haven't reproduced it since.

**Comment by sorenhan** [comment]
Reopening this - I was going to write a cleaner bug describing the case, but reopening this is probably more correct,. to keep tracking. I *think* the bug will not happen anymore in the functional tests as it is
Additional Notes:
1. To reproduce, we need to change the music back to load from the slow/unreliable website.
2. It also seemed to fail until the music file was cached locally, so tests should maybe be done with changing to a new audio file for each test run.
3. This *may* have to do just with audio files, or may be with general downloading of any assets, or just textures/materials (as the downloading code is shared between multiple asset types).
