### ISSUE TITLE
Add "isModerator" property to users

### ISSUE THREAD

**Issue by stevenvergenz** [Microsoft/mixed-reality-extension-sdk#271]

**Comment by willneedit** [comment]
Maybe extend on this, like:

1. Two groups of permissions: "scope" (which would be a single world in Altspace) and "global". When the hosting VR environment offers a single 'room', both sets should yield equal values.
1. Permission in a set could be:
  a. Admin (complete admin/owner powers within the given set, includes all other bits)
  b. Moderator (ability to mute/kick/ban people)
  c. Presenter (increased bandwidth, allowed to operate dedicated media feeds like videos and slides)
  d. Terraformer (Ability to edit/change the environment)
  e. Free Movement (Flying / colliders disabled)

So, for example, a 'presenter' could have a MRE at hand (perhaps literally) which allows him to switch forward/back through slides, but not be able to kick people - that's what a 'moderator' would be for.

**Comment by stevenvergenz** [comment]
This seems a little excessive. Do SDK apps need to know or care about what you can do in Altspace? I think moderator is all you'd need for ~99% of cases. Slides and moderation actions are done in Altspace, and apps don't have visibility into those systems. Also, I don't think there is any utility for MREs to distinguish between global roles and scoped roles. A user either has or hasn't an ability.

**Comment by willneedit** [comment]
Have it and not need it is better than the other way round :) Moderator might be good for many of the use cases, true, but as stated, presenter has some viable use cases, too. Especially for performers to, say, control slides, or stage lighting/effects... you name it.

Though, yes, if you trust someone with the moderator role and its extended permissions, you might extend the same trust to not have him ruin your presentation by randomly pressing the forward/backward buttons.

**Comment by stevenvergenz** [comment]
This feature is now live in Altspace: https://steamcommunity.com/games/407060/announcements/detail/1776015676295906927
