### ISSUE TITLE
Remove "actor-correction" message

### ISSUE THREAD

**Issue by stevenvergenz** [Microsoft/mixed-reality-extension-sdk#289]
This message is redundant with `actor-update`, and is already being converted to such in the latest SDK version.

**Comment by eanders-MS** [comment]
I've been keeping this around because I might use it eventually.

**Comment by eanders-MS** [comment]
The idea is that when the client receives an actor-correction, it will interpolate values rather than overwrite them.

**Comment by stevenvergenz** [comment]
We should remove [rules.ts:221](https://github.com/Microsoft/mixed-reality-extension-sdk/blob/red/packages/sdk/src/adapters/multipeer/rules.ts#L221) then, which indicates that it's deprecated.

**Comment by eanders-MS** [comment]
Sure. I can roll that into my current changes.

**Comment by eanders-MS** [comment]
Addressed in #291
