### ISSUE TITLE
[Functional Tests] Asset Mutability Test: failed to load UVGrid material.

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/mixed-reality-extension-sdk#305]
Multiple users in the scene failed to load the UV grid texture. Error in Altspace log:
`[MRE-SDK] Error: Asset 7db35667-ca47-67a6-6a49-8602585708d2 is not patchable, or not of the right type!`
(This is probably due to attempting to animate the non-loaded texture.)

After restarting the test the texture loaded for everyone.

**Comment by stevenvergenz** [comment]
Fixed in #304
