### ISSUE TITLE
Timeout error occurs when many primitive actors created

### ISSUE THREAD

**Issue by AndreMuis** [microsoft/mixed-reality-extension-sdk#315]
Many "unhandledRejection Connection closed" errors are generated when creating many primitive actors. Code and screenshots attached.

<img width="667" alt="Capture" src="https://user-images.githubusercontent.com/920149/56460580-a6038b00-6359-11e9-859b-a0571d16de07.PNG">

[many-objects.ts.txt](https://github.com/Microsoft/mixed-reality-extension-sdk/files/3100447/many-objects.ts.txt)

**Comment by eanders-MS** [comment]
Right now we put a timeout timer on every message that expects a reply. This might be too strict. I think we could get away with only having timeouts on the following messages:
- heartbeat-reply
- sync-animations (and this payload will be going away with the planned animation sync refactor)
