### ISSUE TITLE
Mac server support

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#32]
Currently MREs can be deployed to Macs just fine, and the logic executes, but static files are not working

Repro steps
1. Deploy Hello World MRE to a mac
2. instantiate it in AltspaceVR
Observed: Hello World text shows up and spins, but cube does not
Expected: Hello World text and cube both show up and spin.

**Comment by eanders-MS** [comment]
Was user error. Mac is working fine.
