### ISSUE TITLE
Remove ForwardPromise from Actor creation calls

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#321]
Our async API has undergone many improvements since the time we introduced ForwardPromise. I'm not sure we need it any more. It would be a nice API simplification if we just returned an id from methods like CreateFromGltf. We would have to reintroduce the `created(): Promise<void>` method so that the ability to wait is still an option.

**Comment by eanders-MS** [comment]
This is based on some feedback that ForwardPromise was confusing.

**Comment by willneedit** [comment]
The Forward Promise doesn't contain just the ID, but the whole actor structure in its value attribute.

Simply returning the ID would make things overly complicated when it comes to doing stuff with the actor - you'd have to do a lookup to get the actor corresponding to the given ID.

**Comment by eanders-MS** [comment]
True! I misstated it above. We would return the Actor itself from the call rather than a ForwardPromise<Actor>. Thanks for catching that detail.
