### ISSUE TITLE
Task: Improve physics synchronization

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#325]
* Non-authoritative peers should not simulate rigid bodies. Just apply transform updates as they're received.
* When a peer becomes authoritative, enable simulation of rigid bodies and start broadcasting transform updates.
* The server should receive the current rigid body positions.

**Comment by sorenhan** [comment]
There are 3 steps:
1. There's a bug making it stutter even in ideal conditions.
2. Gravity can be different if orientation or scale is different between instances.
3. We need an explicit transfer of authoritative peer
4. We ought to implement distributed authority - individual users can take ownership over individual actors (when grabbed, for example).

**Comment by jabenk** [comment]
I think this issue can be closed now.

**Comment by sorenhan** [comment]
Closed as we completed the physics sync upgrade
