### ISSUE TITLE
Unity: Include link.xml in MREUnityRuntime.dll build output

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#329]
This file is required for MREs to work in Unity projects built using the IL2CPP backend, so let's include it in MREUnityRuntime.dll's build output.

Investigate: How does Unity handle multiple link.xml files?

**Comment by tombuMS** [comment]
Many projects need a link.xml project for IL2CPP. Having it as build output would still mean a manual merge of it with the existing link.xml most Unity projects have.

**Comment by tombuMS** [comment]
This is merged in to red and the build server has been updated to copy the link.xml to the build artifacts drop archive.

[Unity PR#197](https://github.com/microsoft/mixed-reality-extension-unity/pull/197)
