### ISSUE TITLE
MRE Unity Client lib doesn't compile against Unity 2018.3 DLLs

### ISSUE THREAD

**Issue by sorenhan** [microsoft/mixed-reality-extension-sdk#332]
If a developer has Unity 2018.3 installed instead of 2018.1, the DLL compiling fails on some Vector2 classes not being found. Downgrading to 2018.1 solved the problem

**Comment by tombuMS** [comment]
@sorenhan How soon do we wish to be supporting the future versions of Unity?  We also should decide how we handle when to drop support for versions of Unity as we move forward.  At some point the API's will diverge such that it would make sense to bump up the minimum version of Unity that we support.

**Comment by stevenvergenz** [comment]
I just built and ran the tests with 2019.2.12f1 and had no problems. Maybe something special with 2018.3?
