### ISSUE TITLE
Emissive factor and texture not supported?

### ISSUE THREAD

**Issue by pinkwerks** [microsoft/mixed-reality-extension-sdk#341]
I was experimenting with materials that didn't use lighting. I was able to create a GLTF that used emissiveFactor and emissiveTexture and it previewed okay in vscode/babylon.js. However, when the file was loaded into altspace, it was rendering black.

**Comment by stevenvergenz** [comment]
TL;DR: This is expected behavior in Altspace.

Altspace uses a simplified material model for mobile performance reasons. It uses a limited vertex-lit shader that supports only a single texture: the glTF `baseColorTexture`.

**Comment by pinkwerks** [comment]
Thanks for clearing that up!

What's the current best way to understand what is and is not supported? For instance, textures aside, does the vertex lit model support emissiveFactor? ie I'd like to make some UI that is not affected by the environment supplied lighting.

**Comment by stevenvergenz** [comment]
The SDK supports the full range of PBR properties as specified by the glTF spec. Altspace only implements a subset of them: `mainColorFactor` and `mainColorTexture`. It is supposed to support the various transparency settings too, but a bug prevents it from working right now. I think an emissive, a.k.a. an unlit single texture, shader is not out of the question though, so I'll reopen this issue to track that feature work.

**Comment by eanders-MS** [comment]
@stevenvergenz Is this done now?

**Comment by stevenvergenz** [comment]
Released in v0.16.
