### ISSUE TITLE
Input (clicks) not working in current release

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#366]
I'm unable to activate any menu items in the functional test app.
* Altspace: Current release on Steam
* Account: Logged in as eanders-ms
* Functional Tests: master branch running locally

When I click on a functional test menu item, nothing happens. Looks like there's an associated error in the Altspace client log:

```
ArgumentNullException: Value cannot be null.
Parameter name: User cannot be null when performing an action
  at MixedRealityExtension.Behaviors.Actions.MWAction.UpdateAction (MixedRealityExtension.Core.Interfaces.IUser user, MixedRealityExtension.Behaviors.Actions.ActionState newState) [0x00003] in <9333852053d24b18b052d53eeb1ab451>:0 
  at MixedRealityExtension.Behaviors.Actions.MWAction.StopAction (MixedRealityExtension.Core.Interfaces.IUser user) [0x00000] in <9333852053d24b18b052d53eeb1ab451>:0 
  at Assets.Altspace.Features.MREApps.Scripts.Behaviors.MREButtonBehavior.<MREButtonBehavior>m__1 (System.Boolean _, System.Boolean isPressed) [0x0003c] in <ea54653d4d5e4e75a3234405367d3e95>:0 
  at AbstractBaseValue`1[T].FireValueChanged (T oldValue, T newValue) [0x00022] in <b63311e65b1949cc838842546badadf8>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
AbstractBaseValue`1:FireValueChanged(Boolean, Boolean)
ValueEventHelper`1:FireIfValueChanged()
ComputedValue`1:FireIfChanged()
TargetableButtonBehaviour:@??@?@A@AAA?@A?@BB@@?AA(TargetableButtonTool, Boolean)
TargetableButtonTool:?B@A?A?BBB?AB@BBA??A@B@(TargetableButtonBehaviour, TargetableButtonBehaviour)
AbstractBaseValue`1:FireValueChanged(TargetableButtonBehaviour, TargetableButtonBehaviour)
MutableValue`1:set_Value(TargetableButtonBehaviour)
BaseMutableValue`1:Set(TargetableButtonBehaviour)
TargetableButtonTool:AA@BB@BAB@A??A@?AA?@ABA(TargetableButtonBehaviour)
TargetableButtonTool:Update()
```

**Comment by eanders-MS** [comment]
More info: The repro seems to involve re-entering a space. Could it be that after re-entering, MRE click behaviors no longer work?

**Comment by stevenvergenz** [comment]
I've never been able to reliably repro this bug, but it seems to be related to *any* unhandled exception in MRE-land. Can also repro this bug by attempting to load an invalid library object.

**Comment by tombuMS** [comment]
Yeah.  I don't think this bug is accurately titled to be input.  Input is just one of the most common places we see this.  I believe this is related to the frozen app state we get in to because of some unhandled exception.

**Comment by eanders-MS** [comment]
Regarding the bug title: the callstack in the client log is related to input, so at least in this instance it is input-specific.

Will see if I can repro again later today. I was hitting it frequently last night, but not 100%.

**Comment by eanders-MS** [comment]
It looks like I have a reliable repro:
- Launch Altspace and go to your home space
- Spawn the funcitonal test app in your homespace
- Try to click on a test menu button - it should work
- Re-enter the space
- Try again to click on a test menu button - if the bug repros, it should not work this time

**Comment by eanders-MS** [comment]
I think I tracked it down (see associated Altspace PR)
