### ISSUE TITLE
Add SDK performance counters

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#374]

**Comment by sorenhan** [comment]
Maybe loaded asset counts (number of actors, meshes, polys, materials, textures, pixels) is the highest priority.
Maybe bandwidth used?

**Comment by sorenhan** [comment]
and number of actors

**Comment by stevenvergenz** [comment]
My proposal for stats to track:
* Actor count
* Prefab count
* Sound count
* Material count
* Texture count
    * Total texture pixels
* Mesh count
    * Total mesh polygons
    * Total mesh vertices
* Average websocket bandwidth in/out over the last 5/30/60 seconds
* Network message count in/out over the last 5/30/60 seconds

**Comment by sorenhan** [comment]
I would also add 
1. "sound time in seconds" - as that's a pretty good measure of how much memory the sound waveforms take up,
2. Active Media Instances. - how many sounds/video streams are currently playing.
