### ISSUE TITLE
[0.12.n bug] Asset unload test

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#395]
Test: 2 player, PC and Quest
- Plain sphere was magenta. After cycling through again, it was white.

**Comment by stevenvergenz** [comment]
Cannot repro in Altspace or on Testbed with 0.12.2. This is the same issue that microsoft/mixed-reality-extension-unity#88 fixed, could the DLLs have been switched, or the timing wrong?

**Comment by eanders-MS** [comment]
Did you test with two clients?
