### ISSUE TITLE
Event listeners don't work in other world spaces

### ISSUE THREAD

**Issue by willneedit** [Microsoft/mixed-reality-extension-sdk#40]
When trying to have an actor listening to events (like onHover and onClick), it only works if the item is created in the home space, but not if the item is created in a new world space.

Reproducible with hello-world example: Works okay (growth/shrink on hover, sideflip on click) in Homespace, but no reaction on user interaction when created in world space (just spins)

(UPDATE): Error is more generalized: When an item is used in more than one worldspace, the first instance I encountered worked correctly, not the second one. "Re-enter space" and "Reset Space" doesn't affect that bug; one has to completely exit AltspaceVR and restart the client.

**Comment by eanders-MS** [comment]
Dup of #14
