### ISSUE TITLE
[red - unity] Crash in rigid body update

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#401]
Perf refactor introduced a regression in rigid body update.
Repro: In MRETestBed, run physics-sim-test

![image](https://user-images.githubusercontent.com/12176807/61845445-23a6cd80-ae58-11e9-8978-06a3f1c7cc6f.png)

**Comment by tombuMS** [comment]
This is fixed in PR#[95](https://github.com/microsoft/mixed-reality-extension-unity/pull/95)
