### ISSUE TITLE
[0.12.n bug] clock sync test: stop/start button does not unload previous assets

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#403]
Pressing stop: previous digits stop animating but aren't unloaded. Pressing play: Duplicate assets are loaded and start animating. Old digits are still visible.

Possible regression in the asset system, or a new bug in the test harness.

**Comment by eanders-MS** [comment]
Was testing in Altspace, mredev branch, running in Unity, single user, with latest 0.12.n DLL built locally.

**Comment by stevenvergenz** [comment]
This is a problem with the stop button, repros on many different tests. Non-fatal.

**Comment by stevenvergenz** [comment]
I seem to recall fixing this, but I can't find the PR where it's fixed. Will verify.
