### ISSUE TITLE
[0.12.n bug] Video player does not pause or seek on non-authoritative clients

### ISSUE THREAD

**Issue by stevenvergenz** [microsoft/mixed-reality-extension-sdk#405]
Works: play, change volume, spatialize, change video, stop
Doesn't work: pause, seek

Tested with Altspace 2D authority, Altspace Quest peer.
Tested with Altspace 2D authority, Altspace 2D peer.

**Comment by eanders-MS** [comment]
Verified this is still broken in v0.12.5. It does not repro in the testbed's synchronization test scene, but was able to repro with multiple AltspaceVR clients.

**Comment by eanders-MS** [comment]
Still occurring in 0.13

**Comment by stevenvergenz** [comment]
Still occurring, but not 100% repro. During testing of 0.13.1 pause/seek worked correctly.

**Comment by eanders-MS** [comment]
Unable to repro in 0.13.2
