### ISSUE TITLE
Multiple actors with the same session id 

### ISSUE THREAD

**Issue by qulingyi** [microsoft/mixed-reality-extension-sdk#443]
I have multiple MRE apps with the same session id and uri, and each of them is making a plane actor with the method: 
```
        this.screen = Actor.CreatePrimitive(this.assets, {
            definition: {
                shape: PrimitiveShape.Plane,
                dimensions: { x: 16 / 9, y: 0, z: 1},
                uSegments: 1,
                vSegments: 4,
            },
            addCollider: true,
```
However, currently only one of them has collider and is clickable. We want all of them to be clickable.

**Comment by sorenhan** [comment]
This can be reproed in test bed when opening the synchronizationtest scene (which has 2 instances running in same host app with same session ID), with for example functional test
