### ISSUE TITLE
Capsule rotation possibly not working

### ISSUE THREAD

**Issue by evhan55** [microsoft/mixed-reality-extension-sdk#465]
We have been using the MRE SDK to place objects in a scene that are rotated.

This line works for a `PrimitiveShape.Box`:
`box.transform.local.rotation = Quaternion.RotationAxis(Vector3.Right(), Math.PI / 6);`
The box rotates 30 degrees.

However, this line doesn't seem to work for a `PrimitiveShape.Capsule`:
`capsule.transform.local.rotation = Quaternion.RotationAxis(Vector3.Right(), Math.PI / 6);`
The capsule does not rotate at all.

Just wanted to report it in case it's useful!

We are working with a version of the SDK forked a couple of months ago.

**Comment by stevenvergenz** [comment]
What is the orientation of your capsule? You'll have a hard time noticing rotations along the main capsule axis.

**Comment by evhan55** [comment]
Thanks, I tried rotating along both `.Right()` and `.Backward()` rotations and saw no effect either time.

```
const capsule = Actor.CreatePrimitive(this.assets, {
	definition: {
		shape: PrimitiveShape.Capsule,
		dimensions: { x: 1, y: 1, z: 1 }
	},
	addCollider: true
});
capsule.transform = new ActorTransform();
capsule.transform.app.position = new Vector3(-0.2, 0, 1.1); // x (width), y (height), z (depth)
capsule.transform.local.scale = new Vector3(0.30, 0.50, 0.30);
capsule.transform.local.rotation = Quaternion.RotationAxis(Vector3.Right(), Math.PI / 6);
```

**Comment by stevenvergenz** [comment]
Oh, this makes total sense now. We have specially set-up observable properties that you're overwriting with `new ActorTransform()`. So none of your transform changes are being picked up. You can set those properties directly in the constructor:

```ts
const capsule = Actor.CreatePrimitive(this.assets, {
	definition: {
		shape: PrimitiveShape.Capsule,
		dimensions: { x: 1, y: 1, z: 1 }
	},
	addCollider: true,
        actor: {
            transform: {
                app: { position: { x: -0.2, z: 1.1 } },
                local: {
                    rotation: MRE.Quaternion.RotationAxis(Vector3.Right(), Math.PI / 6),
                    scale: { x: 0.3, y: 0.5, z: 0.3 }
                }
            }
        }
});
```

One other thing to note, Unity can do some weird things with non-uniform scales on colliders, so the actual behavior might be inconsistent.

**Comment by evhan55** [comment]
@stevenvergenz 

Oh great!
We will try this instead, thank you so much!
I can report a little later on whether this works for us, but it makes sense.

Thanks again.
