### ISSUE TITLE
Unsure how to access cube transformation after grab

### ISSUE THREAD

**Issue by evhan55** [microsoft/mixed-reality-extension-sdk#470]
I am trying to use `grabbable` on an `Actor` and running into this issue where if I try to access the rotation properties on release, the values are not updated to the new transform.

```ts
cube.onGrab('end', () => {
	const c = this.context.actor(cube.id);
	console.log(c.transform.local.position.x);
	console.log(c.transform.local.position.y);
	console.log(c.transform.local.position.z);
	console.log(c.transform.local.rotation.w);
});
```

The printed values are all `0` even though the actor has been moved around.

**Comment by stevenvergenz** [comment]
Local transforms during grab are always 0, since grab is executed in app space. Try checking `c.transform.app.position`. If that's also incorrect, maybe you need to subscribe to transform updates? Though I don't think that's necessary.

**Comment by evhan55** [comment]
Yes, trying `c.transform.app.position` also returns 0 for all values.

Is there documentation for how to subscribe to transform updates?

**Comment by stevenvergenz** [comment]
https://microsoft.github.io/mixed-reality-extension-sdk/classes/actor.html#subscribe

**Comment by evhan55** [comment]
Ah, thank you very much! This worked, and it worked for retrieving both `local` and `app` properties.

The line I had to add was:
```ts
cube.subscribe("transform");
```
