### ISSUE TITLE
Deployment to Azure not working?

### ISSUE THREAD

**Issue by evhan55** [microsoft/mixed-reality-extension-sdk#474]
Hello,

I followed the instructions at https://github.com/microsoft/mixed-reality-extension-sdk/blob/red/DEPLOYING.md to deploy my MRE at a new Azure instance, but it doesn't seem to be working.

The `public/` directory seems to be served fine at [https://pink-box-game.azurewebsites.net](https://pink-box-game.azurewebsites.net).

But when I try to access the MRE in `MRETestBed` via **ws://pink-box-game.azurewebsites.net**, the MRE doesn't load and I don't see my debug output in the Azure log to show that an MRE context is being created on a user connection.

This is my server setup:
```ts
const server = new WebHost({
	baseUrl: 'https://pink-box-game.azurewebsites.net',
	baseDir: resolvePath(__dirname, '../public'),
	port: process.env.PORT
});
```

This is the output on the Azure instance:
```
2020-01-03T17:49:25.473414826Z 2020-01-03T17:49:25.472Z app Node: v10.17.0
2020-01-03T17:49:25.474357130Z 2020-01-03T17:49:25.474Z app @microsoft/mixed-reality-extension-sdk: v0.14.0
2020-01-03T17:49:25.547312240Z 2020-01-03T17:49:25.547Z app Multi-peer Adapter listening on {"address":"::","family":"IPv6","port":8080}
2020-01-03T17:49:25.553088465Z 2020-01-03T17:49:25.547Z app baseUrl: https://pink-box-game.azurewebsites.net
2020-01-03T17:49:25.553359466Z 2020-01-03T17:49:25.553Z app baseDir: /home/site/wwwroot/public
```

**Comment by stevenvergenz** [comment]
You need to use port 8080 (or whatever's configured). So `ws://pink-box-game.azurewebsites.net:8080`, and make sure the port is open in the firewall.

**Comment by evhan55** [comment]
Thanks @stevenvergenz , do you mean that I need to set the `baseUrl` to `ws://pink-box-game.azurewebsites.net:8080` in my server file, or just that I need to use that URL in the MRETestBed?

**Comment by stevenvergenz** [comment]
Both.

**Comment by stevenvergenz** [comment]
Also, if you're using Unity version 2018.2 or earlier, loading resources via HTTPS will not work, you need to use plain HTTP.

**Comment by evhan55** [comment]
@stevenvergenz Thanks, it is still not working. I am assuming there are steps missing in the Deployment instructions for the Azure Deployment, because the web socket doesn't want to connect no matter what. I even set 'Web Socket' to `ON` in the Azure app settings and still nothing.

Thanks again!

**Comment by evhan55** [comment]
@stevenvergenz 

I was finally able to get the MRE deployment on Azure working with the following setup:

```ts
const server = new WebHost({
	baseUrl: 'https://pink-box-game.azurewebsites.net',
	baseDir: resolvePath(__dirname, '../public'),
	port: (process.env.PORT || 80)
});
```

And accessing `ws://pink-box-game.azurewebsites.net:80` in MRETestBed.

The problem I think is that Azure won't serve any WebSocket content over `8080`, only over `80` or `443`, but expects to be able to pink `8080` on startup.  Therefore, the port in the MRE needs to both serve `8080` and `80` at various times, I think?

ping @olga-microsoft ^^

The deployment instructions could use some updating, thanks!

**Comment by olga-microsoft** [comment]
I tried these steps and couldn't make websockets work after following my old steps and these. I was reading that Azure Web App expects only usage of ports 80 or 443, but even that didn't work. HTTP works fine, but websocket connection is rejected with 503. I tried only with a free tier app, maybe it's not a supported feature? I'd contact Azure support for this.

**Comment by tombuMS** [comment]
> I tried these steps and couldn't make websockets work after following my old steps and these. I was reading that Azure Web App expects only usage of ports 80 or 443, but even that didn't work. HTTP works fine, but websocket connection is rejected with 503. I tried only with a free tier app, maybe it's not a supported feature? I'd contact Azure support for this.

@olga-microsoft Did you enable websockets in your web app service configuration?

**Comment by olga-microsoft** [comment]
@tombuMS yes, I did, the first thing. It didn't seem to change anything.

**Comment by evhan55** [comment]
I was working on this a few months ago and found this to work for me at the time for some reason:
https://github.com/evhan55/mixed-reality-extension-sdk-samples/blob/f9752c962447ce104e15678f6071a8d6b00534a7/samples/team-planner/src/server.ts#L21

**Comment by olga-microsoft** [comment]
Confirmed with Azure team that websockets+Linux+free tier is not a supported scenario yet. I will update the instructions.
https://docs.microsoft.com/en-us/answers/questions/61386/can39t-connect-to-a-nodejs-web-app-websocket.html

**Comment by sorenhan** [comment]
Closing this, as the instructions have been updated
