### ISSUE TITLE
Color Attributes Have Invalid Min/Max

### ISSUE THREAD

**Issue by weshoke** [microsoft/mixed-reality-extension-sdk#485]
This should be Math.floor(v.color0.x * 255) etc. instead of v.position in https://github.com/microsoft/mixed-reality-extension-sdk/blob/red/packages/gltf-gen/src/vertexattributes.ts#L232

```
this._min.minimizeInPlace(v.position);
this._max.maximizeInPlace(v.position);
```

**Comment by stevenvergenz** [comment]
Good catch!

**Comment by eanders-MS** [comment]
It seems like the two lines quoted by @weshoke should just be removed from the `writeToBuffer` function. Am I missing their purpose?
