### ISSUE TITLE
Attachment point not working in MRETestBed?

### ISSUE THREAD

**Issue by evhan55** [microsoft/mixed-reality-extension-sdk#486]
Hello, this is referencing a discussion over at https://github.com/microsoft/mixed-reality-extension-unity/pull/42.

I am using the following code in my MRE:
```
const head = Actor.Create(this.context, {
	actor: {
		name: 'Team planning object',
		appearance: {
			meshId: square.id,
			materialId: redMat.id
		},
		attachment: {
			attachPoint: 'head',
			userId: user.id
		}
	}
});
head.subscribe('transform');
```

I am then viewing the MRE in two different contexts: AltspaceVR and the MRETestBed app on HoloLens1.

**Expected**
- Actor attaches to head of joined user, and position of actor updates and is visible in AltspaceVR and in the HoloLens1

**Actual**
- Actor attaches to head of joined user (and position updates) for Altspace users only
- For users joining via HoloLens1, the actor seems to stay in position 0,0,0

**Comment by eanders-MS** [comment]
I wasn't able to repro this running MRETestBed in the Unity editor. Are you certain that `user.id` is valid  at the time you're creating the actor? In my repro attempt, I created the actor in the `onStarted` callback, but had to wait to attach it until the user joined. That meant performing the attach in the `onUserJoined` callback.

**Comment by evhan55** [comment]
Yes, I have this code in the `onUserJoined` callback, and I believe the user.id is valid, and it does work in Altspace. I haven't tried it in the Unity editor, is it possible it behaves differently when deployed to the device?

**Comment by evhan55** [comment]
Also, just out of curiosity, if attachment is a read-only property, how are you able to set the attachment after the actor has been created?

**Comment by eanders-MS** [comment]
Actor has `attach` and `detach` methods.

**Comment by evhan55** [comment]
Oh ok I see them now, thank you!

**Comment by eanders-MS** [comment]
Is the HoloLens user's movement bound to the MRETestBed's camera controller?

**Comment by evhan55** [comment]
I am not sure, it's possible that was one of the small changes I needed to make but I didn't think it was, since I only remember making changes to the input controller. I will look into this and let you know... Thank you!

**Comment by evhan55** [comment]
Hi @eanders-MS 

I looked, and I am not sure if the HoloLens user's movements are bound to the MRETestBed's camera. I am still new to Unity's camera system and have a difficult time understand when things are supposed to be bound in the Unity UI vs. in the scripts/code.

I took a fresh copy of the `MRETestBed` and inserted the `MRTKv2` package into it and moved the camera/player's around to match my understanding of what is needed, and the `socket-right-hand` and `socket-left-hand` do indeed attach to the camera when I click 'Play' in the editor. However, they do not attach when running 'holographic remoting' on the device. This tells me that somehow the Unity editor doesn't quick emulate whatever is going on in the device in terms of the camera/player.

However, this probably does mean that it's not a problem with MRE attachments and a problem with my misunderstanding of Unity and the MRTK camera. Thank you very much for your time! I'll go ahead and close the issue for now.

**Comment by eanders-MS** [comment]
Coincidentally, my teammate @tombuMS has been working on integrating MRTK into the MRETestBed this week, and has it working for WMR headsets. It may be worth a look. https://github.com/microsoft/mixed-reality-extension-unity/tree/tombu/mrtk-testbed

**Comment by evhan55** [comment]
Oh, great! Thank you! I will definitely check it out and give it a go.

**Comment by tombuMS** [comment]
> Oh, great! Thank you! I will definitely check it out and give it a go.

You can find my branch in the repo at [tombu/mrtk-testbed](https://github.com/microsoft/mixed-reality-extension-unity/tree/tombu/mrtk-testbed)

**Comment by evhan55** [comment]
@tombuMS Thank you! I actually already fetched the branch and am trying to load the project in Unity as we speak, so excited! Let me know if you are interested in hearing if I am able to get it to work or run into issues, etc. Happy to provide feedback.

**Comment by evhan55** [comment]
@tombuMS Ok perfect, thanks for the heads up, I will check out the MRTKHelloWorld scene to see how you've got it set up.

**Comment by tombuMS** [comment]
I edited my comment above, just in case you missed it.  You will want the MRTKHelloWorld scene.  I am getting ready to push up two new prefabs that will facilitate adding what you need to any scene you create.

I'll update here once that has been pushed.

**Comment by evhan55** [comment]
Great, thank you very much!

**Comment by tombuMS** [comment]
Ok.  Just pushed up the prefabs.

`Assets/TestBed Assets/Prefabs/MRTK/` is the directory
- `MRE_MixedRealityToolKit` is the prefab for the MRTK game object needed in the scene
- `MRTKControllerWithCursor` is the prefab for the character controller configured for MRTK

**Comment by evhan55** [comment]
Oh my, this is very exciting to hear, thank you!
I spent all day yesterday trying to make these prefabs myself but did not really know how to do it.

I will test these as soon as I can, and see if/how they behave in the HoloLens1.
What MRTK device have these prefabs been tested/written for, if I may ask?
