### ISSUE TITLE
[samples - v0.16.n] Hello World: DoAFlip animation only works the first time

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#515]
In AltspaceVR: The first time the cube is clicked, it correctly plays the DoAFlip animation. For subsequent clicks, the MRE still handles the click event and issues the command to start the animation, but the cube doesn't animate.

**Comment by salahzar** [comment]
I can confirm this, I already have asked in discord group. This is very frustrating when trying to understand how the animations are working in AltspaceVR. Also even if this is a bug somewhere there should be a workaround to have it working.

**Comment by stevenvergenz** [comment]
Fixed by https://github.com/microsoft/mixed-reality-extension-sdk-samples/pull/51. We start the animation on click, but unless you REstart it it just stays at the end.
