### ISSUE TITLE
Using Actor.CreateFromGltf() creates a child actor in Unity but isn't accessible in the Nodejs App

### ISSUE THREAD

**Issue by norybiak** [microsoft/mixed-reality-extension-sdk#516]
When using Actor.CreateFromGltf(), the assets are created on a child actor (GameObject) but isn't accessible in the nodejs app.

It would make sense to apply the assets on the actor that is creating the glTF if it's a single mesh. Otherwise, update Actor.children[] so that each actor is accessible.

Current solution is to use AssetManager.loadGltf() then assigning the loaded assets manually to an empty Actor.

**Comment by stevenvergenz** [comment]
The way glTF in general, and the UnityGLTF loader in particular, is set up is it always creates a GameObject/actor for the scene you're loading, then puts the real contents underneath it. This is a consequence of how glTF itself is structured. The real contents are available, but you have to wait for the creation to complete: `await rootActor.created()`; the root actor will have its children populated by then. If you have more questions, please reopen this issue.
