### ISSUE TITLE
Move math and other generic helpers to a separate package

### ISSUE THREAD

**Issue by jtfell** [microsoft/mixed-reality-extension-sdk#518]
Great work on the `gltf-gen` library. Its perfect for for embedding in other projects and is working brilliantly for me. There is just one frustrating limitation. I can barely believe this is the chain of issues to be honest:

- `gltf-gen` depends on `mixed-reality-extension-sdk`
- `mixed-reality-extension-sdk` depends on `restify`
- `restify` modifies the global `Request` prototype https://github.com/restify/node-restify/issues/1540
- My `express` server (which requires in a module that depends on `gltf-gen`) has the wrong object for `req.query`

This is clearly an issue with `restify` (and has been open there since 2017) but I believe there is an easy fix to be had here. I suggest:

- Create new package in this repo (eg. `shared` or `utils`)
- Move the math classes across to this self-contained package with no dependencies
- `gltf-gen` depends on the shared package (and not the main sdk anymore)

I'm happy to draft up a PR if this is something you would be receptive to. Cheers!

**Comment by eanders-MS** [comment]
Your proposed solution works for consumers of `gltf-gen`, and what you're suggesting makes sense on its own given that `gltf-gen` only needs the SDK for the math library. But it sounds like the MRE SDK might be propagating Restify's egregious side effects, and that's something we'd want to avoid. Removing the SDK's dependency on Restify is an option, but we'd need a repro to really understand what's happening. Could you share a minimal repro, or your code if it's open source?

**Comment by jtfell** [comment]
You can see the behaviour here: https://github.com/jtfell/vr-repo

If you comment out the `require('@microsoft/gltf-gen')` line, the `req.query` object is different
