### ISSUE TITLE
Openode not recognized

### ISSUE THREAD

**Issue by JLaureantiPNNL** [microsoft/mixed-reality-extension-sdk#526]
Opened admin terminal:
C:\WINDOWS\system32>npm install -g openode
npm WARN deprecated sha1-file@1.0.4: Development of this module has been stopped.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
C:\Users\laur942\AppData\Roaming\npm\openode -> C:\Users\laur942\AppData\Roaming\npm\node_modules\openode\bin\index.js
+ openode@2.0.17
updated 1 package in 6.12s

Changed to my directory >openode deploy
'openode' is not recognized as an internal or external command,
operable program or batch file.

I have node installed. 
>node
Welcome to Node.js v12.16.1.
Type ".help" for more information.

Help please

**Comment by sorenhan** [comment]
I can't repro the problem. For me it installs fine. After installation I find openode and openode.cmd listed in 2 places in my path (in a command prompt type "where openode"). I can find them in C:\Program Files\nodejs and in C:\Users\<username>\AppData\Roaming\npm\
Suggested steps: 
1. you can check that those files exist in those two folders. If not, installation failed, and maybe try again?
2. check that those two folders are on your path (in a command line use "path"). If not, you can manually add that folder to the path.
