### ISSUE TITLE
Enable/Disable actor functionality (behavior/colliders)

### ISSUE THREAD

**Issue by sorenhan** [microsoft/mixed-reality-extension-sdk#53]
Flag needs control behavior for all child actors recursively

**Comment by eanders-MS** [comment]
I would add: Children should reflect parent state unless the child itself has been explicitly set enabled or disabled. So it's a tri-state value: Enabled, Disabled, Inherit

**Comment by sorenhan** [comment]
I think this would share a lot of the functionality of #30.

I'm not sure I agree with Eric that a tri-state value is required, and I think many game engines may not support enabling a child if a parent is disabled. The most important subset would be enable/disable

I removed "collision" because I don't think we should worry about physics/collision at this time.

**Comment by stevenvergenz** [comment]
Visibility is implemented as of 0.8. Behaviors don't support enable/disable yet, but colliders do which accomplishes the same thing I think. Is this issue fixed?

**Comment by eanders-MS** [comment]
Rendering is done. Need design for colliders.

**Comment by eanders-MS** [comment]
Colliders now support enable/disable.
