### ISSUE TITLE
Testbed should contain pre-built runtime DLLs

### ISSUE THREAD

**Issue by sorenhan** [microsoft/mixed-reality-extension-sdk#553]
Developers shouldn't have to compile their own dll if they are just checking out the SDK. Until we are ready to offer alternative download solutions (Unity Store, Nuget package etc), we should just include the DLL into the GitHub repository, and include that as part of our manual build steps.

**Comment by tombuMS** [comment]
Merged in to master [PR#191](https://github.com/microsoft/mixed-reality-extension-unity/pull/191)
