### ISSUE TITLE
[text-test] "pixelsPerLine" and "font" do not change

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#559]
![2020-04-29_10-01-06](https://user-images.githubusercontent.com/12176807/80624401-7a9d8c80-8a00-11ea-887c-5b90a0b6ac68.gif)

**Comment by stevenvergenz** [comment]
`pixelsPerLine` is only used for rasterized text, and not for SDF text like the test bed and Altspace use, so this is desired behavior.

`font` was recently updated. Which commits of the SDK and DLL is this using?

**Comment by eanders-MS** [comment]
SDK: https://github.com/microsoft/mixed-reality-extension-sdk/commit/0a872642dd85728635122a2bf8707829a118103c
Unity: https://github.com/microsoft/mixed-reality-extension-unity/commit/f6b4415c168ab8b77a04001bd6273440300e08cc

**Comment by stevenvergenz** [comment]
I just tried it on those same commits and it worked as expected. You're sure you rebuilt, and the fonts are populated on the MRE Component in the scene you're using to test?
![fonts](https://user-images.githubusercontent.com/1882376/80630098-8f7e1e00-8a08-11ea-9db6-fd07387168ed.gif)

**Comment by eanders-MS** [comment]
SynchronizationTest, but only one instance active.

**Comment by stevenvergenz** [comment]
Hmm, that works for me too. Did you recompile the DLL?

**Comment by eanders-MS** [comment]
Yes I recompiled the DLL. I'll clean and rebuild.

**Comment by eanders-MS** [comment]
Oh the fonts are gone again from the MRE component! But I fixed that yesterday. Weird.
