### ISSUE TITLE
Feature Request: TeleportTo/InterpolateTo 

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#56]
Ability to instantly teleport (don't collide with anything between old and new positions) and interpolate (moving through space over time, and colliding with any collision geometry on the way)

**Comment by willneedit** [comment]
The feature request ticketed in #65 would offer this function as well: Attach avatar to object, move object, detach object, leaving the avatar at the target location.

**Comment by eanders-MS** [comment]
Fixed by #108
