### ISSUE TITLE
[v0.18.n - animation-sync] failed to sync user on re-enter

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#574]
unhandledRejection TypeError: **Cannot read property 'payload' of undefined**  at constructor.stage:sync-animations (C:\code\Microsoft\mixed-reality-extension-sdk\packages\sdk\built\internal\adapters\multipeer\protocols\clientSync.js:93:50)  at ClientSync.executeStage (C:\code\Microsoft\mixed-reality-extension-sdk\packages\sdk\built\internal\adapters\multipeer\protocols\clientSync.js:167:19)  at ClientSync.run (C:\code\Microsoft\mixed-reality-extension-sdk\packages\sdk\built\internal\adapters\multipeer\protocols\clientSync.js:184:32)  at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by eanders-MS** [comment]
Same callstack occurred in the grab test upon user re-enter.

**Comment by norybiak** [comment]
Within ClientSync.ts

Animations created from a gltf are never added to animationCreatorSet. The bellow will fix the issue but I'm not sure if it's the desired outcome.

```javascript
    if (anim.update && (!createMessage || (createMessage && createMessage.payload.type !== 'create-animation-2'))) {
        super.sendMessage(anim.update);
    }


```

**Comment by stevenvergenz** [comment]
@norybiak Good thought, but I don't think that's it. The `create-from-prefab` rule adds the message to the animation creators, so it should exist by the time the `object-spawned` comes back.

**Comment by stevenvergenz** [comment]
Sigh, found it. I was trying to look up the animation creator message by the animation ID, not the creator message ID. PR coming soon.
