### ISSUE TITLE
Material backface culling/no culling

### ISSUE THREAD

**Issue by sorenhan** [microsoft/mixed-reality-extension-sdk#60]
Be able to dynamically create and apply materials to geometry.
set/update GLTF textures or colors (albedo/metalroughness/normal/occlusion/emissive)?

**Comment by shaneharris** [comment]
Many Shane's Editor users use planes as floors and spheres/boxes as sky boxes. If the above basic primitives at least supported the following;

Repeat X,Y
Offset X,Y
Backface/Doubleface

That would make back porting existing content much easier.

**Comment by stevenvergenz** [comment]
@shaneharris This is mostly done. We don't have a back-face or double-face mode right now, but we have an inverted sphere primitive.
