### ISSUE TITLE
Unity client DLL does not compile in VS 2019

### ISSUE THREAD

**Issue by stevenvergenz** [microsoft/mixed-reality-extension-sdk#600]
From a clean working directory of `red` branch, the MREUnityRuntimeLib solution opens and "builds" without error in VS 2019, but produces no output (bin/Debug is created but empty), and the post-build script is not run.

**Comment by tombuMS** [comment]
This is also the case for an existing working repo when you try to move over to VS 2019 as well.  I will look in to getting everything running in VS 2019.
