### ISSUE TITLE
[v0.19.n] Non-rigidbody primitives are not grabbable

### ISSUE THREAD

**Issue by stevenvergenz** [microsoft/mixed-reality-extension-sdk#603]
* `animation-dynamic` - Keyframe cubes cannot be grabbed
* `grab` - Left and right cubes cannot be grabbed, but the monkey head can
* `physics-stack-4` - Cubes *are* grabbable

**Comment by jabenk** [comment]
https://github.com/microsoft/mixed-reality-extension-unity/pull/176
should fix this.
