### ISSUE TITLE
SE Interop: Plane, Box and Sphere primitives with materials/textures

### ISSUE THREAD

**Issue by shaneharris** [Microsoft/mixed-reality-extension-sdk#64]
Many Shane's Editor users use planes as floors and spheres/boxes as sky boxes. If the above basic primitives at least supported the following;

Repeat X,Y
Offset X,Y
Backface/Doubleface

That would make back porting existing content much easier.

**Comment by stevenvergenz** [comment]
These primitive geometries are all already supported. The rest is just #60.

**Comment by shaneharris** [comment]
I wasn't sure if that was just intended for GLTF based on the description. I also wanted to include the other material settings. Ill close this in favor of #60 and put my comment there.
