### ISSUE TITLE
SerializedCacheRoot in AssetCache is not assigned.

### ISSUE THREAD

**Issue by fnwinter** [microsoft/mixed-reality-extension-sdk#667]
Is this place to discuss about MRE unity also?
While I was running the ticktacktoe example,
I found there was an issue which is the unity client didn't show the altspace cube.
it's because of AssetLoader.cs line 291
importer.SceneParent = MREAPI.AppsAPI.AssetCache.CacheRootGO.transform;
CacheRootGo is not assigned and It seems cacheRoot in AssetManager is not assigned to AssetCache.
Could we move the cacheRoot to AssetCache and reference the object in AssetManager?
Thank you for reading it.

**Comment by stevenvergenz** [comment]
This is fixed in the working branch (red), but hasn't made it to master. 0.19 apps should still work in that branch, try it out and see if it works.

**Comment by fnwinter** [comment]
> This is fixed in the working branch (red), but hasn't made it to master. 0.19 apps should still work in that branch, try it out and see if it works.

Thank you for the answer. Is red the dev branch?
