### ISSUE TITLE
Offset issues when attaching object to users

### ISSUE THREAD

**Issue by MrPrime87** [microsoft/mixed-reality-extension-sdk#678]
In my MRE, I have an object attaching to people. what is happening is that there is always one person that will have their attached object appear offset compared to everyone else. When I reset the space, a different person will have the offset attached object on them. The person that appears to have an offset attached object can see the object attached to themselves properly, but everyone else will see it as offset.

**Comment by stevenvergenz** [comment]
This was fixed with https://github.com/microsoft/mixed-reality-extension-unity/pull/228, and shipped live in Altspace in 4.0.13.
