### ISSUE TITLE
Add procedural glTF handlers to WebHost

### ISSUE THREAD

**Issue by stevenvergenz** [Microsoft/mixed-reality-extension-sdk#69]
Though [gltf-gen](https://www.npmjs.com/package/@microsoft/gltf-gen) exists, there's currently no way to use it in an MRE. I want to add a method to WebHost where you can get a binary blob registered with a URL for clients to load it. This would let you generate a buffer from a GLTFFactory, then load it via `Actor.CreateFromGLTF`.

**Comment by sorenhan** [comment]
This would also be useful for other filetypes in the future - generated audio, for example
