### ISSUE TITLE
A WYSIWYG editor plugin

### ISSUE THREAD

**Issue by Shilar** [microsoft/mixed-reality-extension-sdk#707]
It'd be nice for those with little programming experience to be able to edit and create MRE apps via What You See is What You Get, similar to HTTP.

**Comment by sorenhan** [comment]
I think this should be built as an MRE itself. We have this #339 , so I'll close this as a duplicate

**Comment by Shilar** [comment]
Actually, I read that. This is not a duplicate. I'm talking of having an app that can make MRE apps without prior knowledge, whereas the other is making an MRE that can make a scene via json.

**Comment by sorenhan** [comment]
OK, then I must have misunderstood what you mean. I can't quite see what WYSIWYG means for programming. Can you explain in much more detail what you're thinking of here? Are you talking about visual programming like Kodu or MakeCode? react-like layout functionality and hotloading? Are there any examples from other apps or programming environments that you can point to?

**Comment by Shilar** [comment]
What I'm thinking of is similar to an html editor with WYSIWYG, or some of the Game Makers for those with no or little experience coding. A program that can have the ability to guide what you need and possibly allows visual representation of the program while you code it, or have things similar to "blocks" you can move in that allows for making an MRE without simply toying around in the dark trying to get it to work. That way, once done you have the ability to make an MRE from as simple as the "Hello World" MRE, to complex ones like Holograms Against Humanity or similar card games.
