### ISSUE TITLE
Changes in the code (MRE) are not reflected in Altspace VR

### ISSUE THREAD

**Issue by likhita-biyyala** [Microsoft/mixed-reality-extension-sdk#753]
I have downloaded the code from git-hub & have done the setup required and have successfully executed hello-world application in local server ,and then i have made some changes in the content of text "Hello World" to "Hello world MRE" or some other content i have given saved the file and restarted the local server , but still those changes are not reflected in the application in Altspace VR , still "Hello World"  text coming out in the AltspaceVR app. Any idea why this issue is happening ??

**Comment by cweseloh** [comment]
Did you build the ts files after you saved them?
