### ISSUE TITLE
Figure out why functional test deploy to openode requires tslib dependency

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#81]
The functional tests seem to have a dependency when deploying to openode.io. For some reason this does not show up as a dependency in local builds. 
The package exists locally as it is used as a dev dependency by tslint/typescript, so it may be because of that, combined with Lerna?

Either way, we should figure out why it's needed and why our local build don't complain about it.

**Comment by eanders-MS** [comment]
Yes it's because the project is part of the monorepo managed by lerna. The project isn't setup to be independently deployed.
