### ISSUE TITLE
text.contents changes are lost if not resolving promise first

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/mixed-reality-extension-sdk#90]
The following code
        const textPromise = Actor.CreateEmpty(this.app.context, {
            actor: {
                text: {
                    contents: "Original Text",
                }
            }
        });
        textPromise.value.text.contents = "New Text";
does not show the right text
Expected result: it displays "new text"
Observed result: it shows "original text"
It behaves as expected if inserting 
await textPromise;

**Comment by willneedit** [comment]
Possibly related: #87

**Comment by willneedit** [comment]
Did you use that snippet in a handler for context.onStarted() ? If so, please try it in context.onUserJoined() and see if there is a difference.

**Comment by eanders-MS** [comment]
I believe this is happening due to a bad interaction between how we detect changes made to the actor vs. how we wait for the actor create process to complete. We're essentially throwing away the dirty flag during that time.
