### ISSUE TITLE
Expose information about the MRE's environment in Context.onStarted()

### ISSUE THREAD

**Issue by willneedit** [Microsoft/mixed-reality-extension-sdk#96]
Close to #59, but this extends on it and may provide a possible way to do it:

Context.onStarted() is called once for every spawned instance of the MRE, regardless where it is. There one can pass an environment block containing information about its current root transformation as well as other information like the SID of the world it's spawned in.

Only caveat would be that the MRE wouldn't notice if it has been moved/rotated/scaled after spawning.

**Comment by sorenhan** [comment]
@willneedit could you give some examples of what you would want to use this for? 
The MRE instance itself isn't tied to a world ID, or world coordinate. In theory users can be in 2 separate worlds, and playing the same MRE with the same SessionID. It's only something each user knows. We could add in some additional properties during onUserJoined, but it wouldn't necessarily be reliable.

**Comment by willneedit** [comment]
Actual use case is the Stargate and the dialing computer - two distinct MRE's which need to communicate with each other and would have to do some 'pairing' when being placed in the same environment. I've made it with a workaround on checking the name of the user triggering the loading of the MRE - since a user cannot be in two places at once.

Currently I have to wait for the very first user connecting after a distinct instance has been spawned and take the data from there, so having that data block (maybe as part of or in addition to the entire user structure) being passed with onStarted() could be a convenience.

**Comment by eanders-MS** [comment]
It is complicated by the fact that a single MRE session can exist in multiple spaces at the same time. The app's root transform and world SID can differ per user.

**Comment by willneedit** [comment]
Right, it would only convey information about the very first space it would be spawned in.

I think a possible idea would be something like onMoved(), where the MRE would receive the world's SID plus an index number or GUID, including the initial placement of the object within its target worldspace.

The additional index would account for the possibility that someone spawned more than one copy of the MRE using the same SID in a single worldspace.

This would also be useful if there'd ever be the possibility for MRE's to be spawned/despawned and moved by external means other than direct user interaction.

**Comment by stevenvergenz** [comment]
This is done, though not quite this way. The space info is exposed through `User.properties`.
