### ISSUE TITLE
Choppy animation for 'watching' users.

### ISSUE THREAD

**Issue by willneedit** [Microsoft/mixed-reality-extension-sdk#98]
For the 'Gate, I do have a rotation animation with keyframes added in for easing in and out.

- The person first entering an empty world (and thus starting the MRE) has no issues with the animation.
- Every other person following the first one sees the animation as choppy or not starting.

Additional info:
- Keyframes for easing in/out are added every 1/3rd of a second, so maybe network latency is an issue?

Maybe related to #13

**Comment by willneedit** [comment]
I used a cycle of

```
Actor.stopAnimation('name');
Actor.createAnimation('name',...);
Actor.startAnimation('name',...);

```

to replace the animation for the next part of the sequence. Moving the Actor.stopAnimation() below, after waiting for the projected animation time + 200 ms, did work around this issue.

**Comment by eanders-MS** [comment]
Glad you found a solution. PR #108 introduces `Actor.animateTo`, which supports ease in/out. I think it might solve this issue for you without need for a workaround.

**Comment by willneedit** [comment]
Looks interesting, and removes the headache with the ease-in/ease-out of the rotation. I'll definitely give it a spin and see where it goes :)

**Comment by eanders-MS** [comment]
Were you starting/stopping multiple animations? Or were all keyframes in a single animation? If multiple animations, this choppiness behavior would have been expected for watching users.

**Comment by willneedit** [comment]
It was a single animation, yet I recycled the name when I started the next phase of the dialing. Perhaps that's what threw off the clients, referring to an old instance by the same name due to network latencies.

**Comment by eanders-MS** [comment]
Interrupting the current animation with a new one would cause a visible jump to the new starting keyframe. I think you'll have better luck with `animateTo`, which starts from the current position.

**Comment by eanders-MS** [comment]
Closing.
